[package]
name = "geospatial_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
dotenvy = "0.15.7"
futures = "0.3.31"
mongodb = "3.2.3"
serde = "1.0.219"
tokio = { version = "1.44.1", features = ["full"] }
